FROM docker.io/golang:alpine as build
RUN apk --no-cache add ca-certificates

FROM scratch
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY ./local/og-describer-cohereaiai ./
ENTRYPOINT [ "./og-describer-cohereaiai" ]
CMD [ "./og-describer-cohereaiai" ]